# Generated by Django 3.2.3 on 2021-09-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='replies',
        ),
    ]
