# Generated by Django 3.2.3 on 2021-09-28 16:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_reply_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=None, verbose_name='Treść postu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Tytuł'),
        ),
    ]
