# Generated by Django 3.2.3 on 2021-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=255, unique=True)),
                ('drugingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('drugindications', models.CharField(blank=True, max_length=255, null=True)),
                ('drugdosage', models.CharField(blank=True, max_length=255, null=True)),
                ('drugcontrindications', models.CharField(blank=True, max_length=255, null=True)),
                ('drugwarnings', models.CharField(blank=True, max_length=255, null=True)),
                ('druginteractions', models.CharField(blank=True, max_length=255, null=True)),
                ('drugpregnancy', models.CharField(blank=True, max_length=255, null=True)),
                ('drugadverse', models.CharField(blank=True, max_length=255, null=True)),
                ('drugoverdose', models.CharField(blank=True, max_length=255, null=True)),
                ('drugaction', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'drugs',
                'managed': False,
            },
        ),
    ]
