# Generated by Django 3.2.3 on 2021-09-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210910_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
