# Generated by Django 3.2.3 on 2021-09-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
