# Generated by Django 3.2.3 on 2021-09-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_drugs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'managed': False},
        ),
    ]
