# Generated by Django 3.2.3 on 2021-09-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_drugs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'managed': True},
        ),
    ]
